Adjust chart packaging script... This ensures we have methods to edit/update charts properly. Removes publishing helm-project-operator charts

diff --git a/scripts/package-helm b/scripts/package-helm
--- a/scripts/package-helm
+++ b/scripts/package-helm
@@ -1,6 +1,5 @@
 #!/bin/bash
 set -e
-set -x
 
 if ! hash helm 2>/dev/null; then
     echo "Helm is not installed"
@@ -13,36 +12,32 @@ source "$(dirname "$0")/util-team-charts"
 
 cd "$(dirname "$0")/.."
 
-# We don't do the full process for prometheus-federator
-if [[ "${BUILD_TARGET}" == "prometheus-federator" ]]; then
-  # Fetch asset from github OB charts repo
-  fetch-team-chart "rancher-project-monitoring" "$RANCHER_PROJECT_MONITORING"
-
-  rm -rf build/charts
-  cp -rf charts build/
-
-  if [[ "$REPO" != "rancher" ]]; then
-    echo "Using custom repo: $REPO to build chart"
-    edit-chart ./build/charts/prometheus-federator/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}" "${REPO}"
-  else
-    edit-chart ./build/charts/prometheus-federator/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
-  fi
-  if ! package-chart ./build/charts/prometheus-federator ./build/charts ; then
-    echo "package-chart failed..."
-    exit 1
-  fi
-  exit
-fi
-
-# TODO: get to the point where this can be removed
 if [ "$BUILD_TARGET" == "helm-project-operator" ]; then
-  DEFAULT_CHART_SOURCE="./packages/$BUILD_TARGET/charts"
-elif [ "$BUILD_TARGET" == "helm-locker" ]; then
-  DEFAULT_CHART_SOURCE="./examples/$BUILD_TARGET/helm-locker-chart-example"
+  echo "$BUILD_TARGET is not a valid target for this script"
+  exit 1
 fi
 
-clean-old-charts "$BUILD_TARGET"
-cp -rf "${DEFAULT_CHART_SOURCE}" "./build/charts/${BUILD_TARGET}"
+if [ "$BUILD_TARGET" == "helm-locker" ]; then
+  echo "Preparing helm-locker dev chart"
+  DEFAULT_CHART_SOURCE="./examples/$BUILD_TARGET/helm-locker-chart-example"
+  clean-old-charts "$BUILD_TARGET"
+  cp -rf "${DEFAULT_CHART_SOURCE}" "./build/charts/${BUILD_TARGET}"
+  hl-edit-chart "./build/charts/${BUILD_TARGET}/Chart.yaml" "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
+  package-chart "./build/charts/${BUILD_TARGET}"
+  exit 0
+fi
 
-edit-chart "./build/charts/${BUILD_TARGET}/Chart.yaml" "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
-package-chart "./build/charts/${BUILD_TARGET}"
+echo "Preparing Prometheus Federator release chart"
+clean-old-charts "$BUILD_TARGET"
+cp -rf charts build/
+
+if [[ "$REPO" != "rancher" ]]; then
+  echo "Using custom repo: $REPO to build chart"
+  edit-chart ./build/charts/prometheus-federator/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}" "${REPO}"
+else
+  edit-chart ./build/charts/prometheus-federator/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
+fi
+if ! package-chart ./build/charts/prometheus-federator ./build/charts ; then
+  echo "package-chart failed..."
+  exit 1
+fi
