Make it possible to set custom REPO on the built chart

diff --git a/scripts/package-helm b/scripts/package-helm
--- a/scripts/package-helm
+++ b/scripts/package-helm
@@ -17,11 +17,24 @@ cd "$(dirname "$0")/.."
 if [[ "${BUILD_TARGET}" == "prometheus-federator" ]]; then
   # Fetch asset from github OB charts repo
   fetch-team-chart "rancher-project-monitoring" "$RANCHER_PROJECT_MONITORING"
-  PROM_FED_CHART=$(newest-chart-version "prometheus-federator")
-  fetch-team-chart "prometheus-federator" "$PROM_FED_CHART"
+
+  rm -rf build/charts
+  cp -rf charts build/
+
+  if [[ "$REPO" != "rancher" ]]; then
+    echo "Using custom repo: $REPO to build chart"
+    edit-chart ./build/charts/prometheus-federator/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}" "${REPO}"
+  else
+    edit-chart ./build/charts/prometheus-federator/Chart.yaml "${HELM_CHART_VERSION}" "${HELM_IMAGE_TAG}"
+  fi
+  if ! package-chart ./build/charts/prometheus-federator ./build/charts ; then
+    echo "package-chart failed..."
+    exit 1
+  fi
   exit
 fi
 
+# TODO: get to the point where this can be removed
 if [ "$BUILD_TARGET" == "helm-project-operator" ]; then
   DEFAULT_CHART_SOURCE="./packages/$BUILD_TARGET/charts"
 elif [ "$BUILD_TARGET" == "helm-locker" ]; then
